Script started on 2021-03-05 13:50:41-0500
]0;jr232@gold14: ~/Desktop/cs214/labs/05/extraCredit/src[01;32mjr232@gold14[00m:[01;34m~/Desktop/cs214/labs/05/extraCredit/src[00m$ clojure
Clojure 1.10.1
user=> (def squareSquare (fn [x] (* x x x x)))
#'user/squareSquare
user=> (squareSquare 2)
16
user=> (squareSquare -2)
16
user=> s (squareSquare 3)
81
user=> (squareSquaer  re -3)
81
user=> 
]0;jr232@gold14: ~/Desktop/cs214/labs/05/extraCredit/src[01;32mjr232@gold14[00m:[01;34m~/Desktop/cs214/labs/05/extraCredit/src[00m$ exit

Script done on 2021-03-05 13:51:32-0500
