TemperatureTester: Temperature.class TemperatureTester.class

Temperature.class: Temperature.java
	javac -deprecation Temperature.java

TemperatureTester.class: TemperatureTester.java
	javac -deprecation TemperatureTester.java

clean:
	rm -f *.class *~ *# *.o

